<%@ Page Title="RecipesGrid" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RecipesGrid.aspx.cs" Inherits="MasterChef.Web.Admin.RecipesGrid" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
	<asp:UpdatePanel ID="UpdataPanel" runat="server">
		<ContentTemplate>
			<h3 class="text-center alert alert-dismissable alert-info" id="headerInfo" runat="server">Recipes Grid</h3>
			<div class="row">
				<div class="col-md-12">
					<asp:GridView CssClass="table table-striped table-hover table-bordered table-responsive"
						ID="gridView" runat="server" DataSourceID="EntityDataSourceProvider"
						AllowPaging="True" AllowSorting="True"
						AutoGenerateColumns="false"
						AutoGenerateDeleteButton="true"
						AutoGenerateEditButton="true">
						<Columns>
							<asp:BoundField DataField="ID" HeaderText="Id" ReadOnly="True" SortExpression="Id"></asp:BoundField>
							<asp:BoundField DataField="ImageID" HeaderText="ImageID" SortExpression="ImageID"></asp:BoundField>
                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name"></asp:BoundField>
							<asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description"></asp:BoundField>
                            <asp:BoundField DataField="Latitude" HeaderText="Latitude" SortExpression="Latitude"></asp:BoundField>
                            <asp:BoundField DataField="Longitude" HeaderText="Longitude" SortExpression="Longitude"></asp:BoundField>							
							<asp:BoundField DataField="CreatorID" HeaderText="CreatorID" ReadOnly="True" SortExpression="CreatorID"></asp:BoundField>
                            <asp:BoundField DataField="CreatedOn" HeaderText="Created On" ReadOnly="True" SortExpression="CreatedOn"></asp:BoundField>
						</Columns>
					</asp:GridView>
					<ef:EntityDataSource runat="server" ID="EntityDataSourceProvider"
						OnContextCreating="dataSource_ContextCreating"
						EntitySetName="Recipes"
						EnableDelete="true" EnableInsert="true" EnableUpdate="true">
					</ef:EntityDataSource>
				</div>
			</div>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>

